### ISSUE TITLE
new Operator does work in SSJS

### ISSUE THREAD

**Issue by shdinx** [JoernBerkefeld/SFMC-Cookbook#1]
```
/* fails with 500 */
function MyClass() {
    var service = {
        attr1: true,
        method1: function(){…}
    };
    return service;
}
var myInstance = new MyClass();
myInstance.method1();
```

"new" operator is allowed in SSJS

```
function MyClass() {
    this.service = {
        attr1: true,
        method1: function(){}
    };
}

var myInstance = new MyClass();
myInstance.method1();
```
The above works fine

The 500 you get is the following:
Jint.Native.JsException: Object expected: method1\r\nException of type 'Jint.Native.JsException' was thrown. - from Jint\r\n\r\n

Please read https://stackoverflow.com/questions/1646698/what-is-the-new-keyword-in-javascript to understand why your approach will fail. It also fails in native Javascript with a response of "undefined".

**Comment by JoernBerkefeld** [comment]
hi Sascha, looked up your email360 lib before seeing this issue and the first thing that I noticed was you using the new operator - was actually just about to look through your code to figure out how you made that work :D 

I've been using the failing version in JS since I first started with AngularJS back in 2016, means I'm pretty sure that works in modern JS. Proof me wrong but I believe it's literally in the style guide for that (admittedly now outdated) AngularJS.

With that said, I'm really happy that you help me understand how that does in fact work in SSJS! thanks a lot! :)
I will update the guide to show your examples!

**Comment by shdinx** [comment]
Hi Joern,

you are right - my bad with the false code. It is working but I was to lazy to write the inner function proper so it failed with undefined.... my bad.

SSJS is using JINT extension with JS ECMAScript 3 from 1999. Many parts such as JSON methods have not been baked into JS so Exacttarget has created their own versions of them. Unfortunately, many of these methods have issues and/or are different from their modern counter parts these days.

The object orientated way of initialising a class and assign method and functions is suffering from this as well.
You can use the new operator but only access values which are declares in its scope with "this."

**Comment by JoernBerkefeld** [comment]
hi @shdinx - sadly it took me until now to finally update that... but it's online now and I'm glad you corrected it! :)

**Comment by JoernBerkefeld** [comment]
@shdinx 
call me lazy but i just noticed this when going over the docs and wanted to run it by you instead of re-testing it, assuming that you will likely know this by heart:

in your 2021 comment you wrote that the following should work.

```
function MyClass() {
    this.service = {
        attr1: true,
        method1: function(){}
    };
}

var myInstance = new MyClass();
myInstance.method1();
```

however, I was wondering if that's actually true? is SSJS really happening to look for `this.service.method1` to run `myInstance.method1()`? 

Could it be that the following is indeed correct instead?

```
function MyClass() {
    this.attr1 = true;
    this.method1= function(){};
}

var myInstance = new MyClass();
myInstance.method1();
```
